### ISSUE TITLE
Problem Nesting blocks from static method

### ISSUE THREAD

**Issue by bmulvihill** [myst-lang/myst#109]
The follow code raises an error that seems to stem from a scope issue:
```ruby
deftype Test
  defstatic hello(&block)
    block()
  end
end

i = 0

Test.hello do
  10.times do
    i += 1
  end
end
```

`Uncaught Exception: No variable or method `i` for Test:Test`

**Comment by faultyserver** [comment]
Very interesting. I don't really have any idea what would be causing this. You mentioned in discord that it works when the method is an instance method rather than a static method, which pretty much rules out my initial thought of doubly-nested blocks just having issues with closures over the root scope.

I'll try to look more into this tomorrow afternoon.

**Comment by faultyserver** [comment]
I wonder if this could be an issue with `scope` vs `instance_scope` on Types. See this code:

https://github.com/myst-lang/myst/blob/2fd6706f1e9168fcca358c91c872370f4db08e2d/src/myst/interpreter/nodes/def.cr#L4-L15

Maybe `scope` doesn't have the same parent as `instance_scope`, and so it loses lexical context? That shouldn't be an issue though, because `block` should close over the lexical scope, not the semantic one.

**Comment by faultyserver** [comment]
My suspicion that this has something to do with static vs instance scopes has been furthered by the fact that this works when `Test` is a module instead of a type:

```myst
defmodule Test
  def hello(&block)
    block()
  end
end

i = 0

Test.hello do
  10.times do
    i += 1
  end
end

IO.puts(i) #=> 10
```

Going to properly start looking into this now.
